apiVersion: apps/v1
kind: Deployment
metadata:
  name: evidence-processor
  namespace: legal-sim
  labels:
    app: evidence-processor
    component: processor
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evidence-processor
  template:
    metadata:
      labels:
        app: evidence-processor
        component: processor
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: evidence-processor
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: evidence-processor
        image: legal-sim/evidence-processor:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          name: http
          protocol: TCP
        env:
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "8001"
        - name: LOG_LEVEL
          value: "INFO"
        - name: OTEL_SERVICE_NAME
          value: "evidence-processor"
        - name: OTEL_SERVICE_VERSION
          value: "v1.0.0"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: url
        - name: STORAGE_URL
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: url
        - name: STORAGE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: access-key
        - name: STORAGE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: secret-key
        - name: TESSERACT_PATH
          value: "/usr/bin/tesseract"
        - name: FFMPEG_PATH
          value: "/usr/bin/ffmpeg"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: shared-storage
          mountPath: /shared
        - name: config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: tmp
        emptyDir: {}
      - name: shared-storage
        persistentVolumeClaim:
          claimName: shared-storage-pvc
      - name: config
        configMap:
          name: evidence-processor-config
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "legal-sim/workload"
        operator: "Equal"
        value: "compute"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - evidence-processor
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: evidence-processor
  namespace: legal-sim
  labels:
    app: evidence-processor
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: evidence-processor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: evidence-processor
  namespace: legal-sim
  labels:
    app: evidence-processor
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: evidence-processor-config
  namespace: legal-sim
  labels:
    app: evidence-processor
data:
  ocr_engine: "tesseract"
  asr_engine: "whisperx"
  max_concurrent_processing: "5"
  processing_timeout_minutes: "30"
  supported_formats: "pdf,jpg,png,wav,mp3,mp4"
  confidence_threshold: "0.8"
