apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: legal-sim-production

resources:
- ../../base

# Production-specific patches
patchesStrategicMerge:
- api-gateway-production-patch.yaml
- evidence-processor-production-patch.yaml
- render-orchestrator-production-patch.yaml
- ingress-production-patch.yaml
- monitoring-production-patch.yaml

# Production-specific configurations
configMapGenerator:
- name: production-config
  literals:
  - environment=production
  - log_level=WARNING
  - debug_mode=false
  - metrics_enabled=true
  - tracing_enabled=true

secretGenerator:
- name: production-secrets
  literals:
  - jwt-secret=production-jwt-secret-key
  - database-password=production-db-password
  - storage-access-key=production-storage-access-key
  - storage-secret-key=production-storage-secret-key

# Resource overrides for production
patches:
- target:
    kind: Deployment
    name: api-gateway
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 5
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "512Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "500m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "1Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "1000m"

- target:
    kind: Deployment
    name: evidence-processor
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 4
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "2Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "1000m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "4Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "2000m"

- target:
    kind: Deployment
    name: render-orchestrator
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "8Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "4000m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "16Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "8000m"

# Production-specific labels
commonLabels:
  environment: production
  team: legal-sim
  cost-center: legal-tech

# Production-specific annotations
commonAnnotations:
  contact: legal-sim-team@company.com
  runbook: https://wiki.company.com/legal-sim/runbooks
  monitoring: https://grafana.company.com/d/legal-sim
